name: clint fuhs
favicon: null
layout_spectrum: 0.02906
typography_spectrum: 0.63198
title: clint fuhs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002949'
    - '#f5f7fc'
    - '#000410'
    - '#abc1dc'
    - '#809ab8'
  brandStrength: 0.25
  lightness: 0.0625
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
