name: clint fuhs
favicon: null
layout_spectrum: 0.5515085919760168
typography_spectrum: 0.5631180952768773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8692298959940672
  lightness: 0.3577588649932295
  saturation: 0.5464166984893382
  rhythmicContrast: 0.5030971055384725
purpose: []
